---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Repeat calling

These settings are for how the base pair level data should be converted into repeat length.

+--------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Setting                        | Description                                                                                                                                                                                                                                               |
+================================+===========================================================================================================================================================================================================================================================+
| Fragment type                  | The overall class in which the data belongs.                                                                                                                                                                                                              |
|                                |                                                                                                                                                                                                                                                           |
|                                | At the moment, there is only a single class that encompasses just HTT trinucleotide repeats. This may expand in the future to include other types of repeats.                                                                                             |
+--------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Assay size without repeat      | The number of nucleotides on either side of the repeat for the assay used. This is then used to calculate the repeat number if the repeat is not being called from positive controls.                                                                     |
+--------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Repeat calling algorithm       | The algorithm used to call repeat length for all peaks in each sample.                                                                                                                                                                                    |
|                                |                                                                                                                                                                                                                                                           |
|                                | *nearest_peak* jumps from peak to peak, using the small distance between peaks to incrementally call repeat size. The resulting called repeats are exactly 1 repeat unit apart.                                                                           |
|                                |                                                                                                                                                                                                                                                           |
|                                | arithmetic_repeat directly calculates the repeat length from base pair size, or corrected base pair size if controls are used to call the repeat. The resulting repeats are not exactly 1 repeat unit apart.                                              |
+--------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Correct repeats using metadata | To indicate whether the known repeat length of the expanded allele in control samples should be used to build a model and correct the repeat length across samples. This requires metadata and will only be an option if metadata are correctly supplied. |
+--------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Allele calling

These settings are for how the modal alleles in the samples should be selected.

The alleles in the sample are broken down into clusters of peaks that we have called "peak regions". The tallest peak within peak regions are then picked out to be the modal allele. Peak regions are identified by two criteria, i) consecutive peaks within a user defined distance from each other ("Gap threshold"), and ii) consecutive peaks above a user defined height threshold ("Peak region height threshold multiplier").

+-----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Setting                                 | Description                                                                                                                                                                                                                                                                                                                                                                                                            |
+=========================================+========================================================================================================================================================================================================================================================================================================================================================================================================================+
| Alleles expected                        | The number of alleles to pick out. Either one or two.                                                                                                                                                                                                                                                                                                                                                                  |
+-----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Selection method                        | How should the peak region for the expanded allele be selected?                                                                                                                                                                                                                                                                                                                                                        |
|                                         |                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                         | If two alleles are expected, the shorter allele will be selected as the first peak region. This setting decides how the expanded allele will then be picked out. In the case of one expected allele, this setting decides how the single allele will be selected.                                                                                                                                                      |
|                                         |                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                         | *Tallest* picks the peak region that has the tallest modal peak (excluding the shorter normal allele).                                                                                                                                                                                                                                                                                                                 |
|                                         |                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                         | *Largest* picks the peak region with the largest sized repeat.                                                                                                                                                                                                                                                                                                                                                         |
+-----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Gap threshold                           | The size between peaks to include within a peak region. For example, with a gap threshold of 6, only peaks within 6 base pairs of the adjacent peak will be included in a peak region.                                                                                                                                                                                                                                 |
+-----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Peak region height threshold multiplier | A multiplier for the height threshold for peaks to be included in the peak region. The height threshold is calculated by finding the mean peak height per sample and multiplying it by this multiplier. Therefore, to make the height threshold more stringent, increase the number. To make the threshold less stringent, decrease the number. For example, to make it 4x less stringent, make the number 0.25 (1/4). |
+-----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                         |                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
