---
output: html_fragment
---

## Tandem Repeat Analysis by Capillary Electrophoresis

This web server is designed to help guide users through a pipeline for short tandem repeat instability analysis from fragment analysis data. The inputs are fsa files or peak tables (eg Genemapper software output), and a user supplied metadata data-frame. This is an app version of our R package [trace](https://zachariahmclean.github.io/trace/), that has the following key features with additional interactivity:

-   Processing fsa files (ladder identification, base pair assignment, peak identification).

-   Identifying alleles and calling repeats.

-   Assigning index peaks and calculating instability metrics (e.g. expansion index or average repeat gain)

## Important experimental considerations

There are several important factors to a successful repeat instability experiment and things to consider when using this package:

-   (required) Each sample has a unique id, usually the file name

-   (optional) Baseline control for your experiment. For example, specifying a sample where the modal allele is the inherited repeat length (eg a mouse tail sample) or a sample at the start of a time-course experiment. This is indicated with a `TRUE` in the `metrics_baseline_control` column of the metadata. Samples are then grouped together with the `metrics_group_id` column of the metadata. Multiple samples can be `metrics_baseline_control`, which can be helpful for the average repeat gain metric to have a more accurate representation of the average repeat at the start of the experiment.

-   (optional) Batch or repeat length correction for systematic batch effects that occur with repeat-containing amplicons in capillary electrophoresis.

    -   Repeat containing amplicons do not run linearly with internal ladder sizes in capillary electrophoresis resulting is an underestimation of repeat length if you just convert from base-pair size. These differences are not always consistent across runs which can result in batch effects in the repeat size. So, if the repeat length is to be directly compared for samples from different runs, this batch effect needs to be corrected. This is only relevant when the absolute size of a amplicons are compared for grouping metrics as described above (otherwise instability metrics are all relative and it doesn't matter that there's systematic batch effects across runs), when plotting traces from different runs, or if an accurate repeat length is desired.

    -   There are two main correction approaches that are somewhat related: either 'batch' or 'repeat' in `call_repeats()`.

        -   Batch correction is relatively simple and just requires you to link samples across batches by indicating them from metadata. But even though the repeat size that is return will be precise, it will not be accurate and underestimates the real repeat length.

        -   By contrast, repeat correction can be used to accurately call repeat lengths (which also corrects the batch effects). However, the repeat correction will only be as good as your sample(s) used to call the repeat length. With how repeat correction works in this app, it's helpful to i) use the same samples across multiple runs (visualizations help you check that correction is consistent across runs), and ii) using multiple samples for correction for each run (helpful to help validate that each sample was called correctly).

Select New to start fresh analysis, or Continue to load in a previous analysis.

```{r, include=FALSE}
#TOODO
## include license or free statement
## provide instructions for how to run localy


```
