---
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## How to upload data

Select the data to upload. There are two steps:

1.  Select the "Data upload type" (see table below).

2.  Select the file(s) to upload.

## Data upload type

| Data upload type | Description                                                                                                                                                                                                                           |
|-------------|-----------------------------------------------------------|
| FSA              | The raw file from the Genetic Analyzer instrument. Must be .fsa file format.                                                                                                                                                          |
| PEAK TABLE       | A table with base pair level data (for example genemapper output). Must be a .csv or .tsv file. Each row must be a called peak and must have three essential columns, i) unique sample id, ii) peak base pair size, iii) peak height. |
| REPEAT TABLE     | A table with repeat level data (for example summarized sequencing data). Each row must be a called repeat and must have three essential columns, i) unique sample id, ii) repeat size, iii) repeat count/height/frequency.            |
| EXAMPLE DATA     | Run an in-built example fsa file experiment                                                                                                                                                                                           |

